${ARM_SIDE_PREFIX}_gravity_compensation_controller_torque:
  ros__parameters:
    type: pal_controllers/GravityCompensationController
    command_joints:
      - ${ARM_SIDE_PREFIX}_1_joint
      - ${ARM_SIDE_PREFIX}_2_joint
      - ${ARM_SIDE_PREFIX}_3_joint
      - ${ARM_SIDE_PREFIX}_4_joint
      - ${ARM_SIDE_PREFIX}_5_joint
      - ${ARM_SIDE_PREFIX}_6_joint
      - ${ARM_SIDE_PREFIX}_7_joint
    root_link: torso_lift_link
    tip_links:
      - ${ARM_SIDE_PREFIX}_tool_link
    torque_gain: 1.0
    parameters:
      ${ARM_SIDE_PREFIX}_1_joint:
        command_interface: "${ARM_SIDE_PREFIX}_1_joint_inertia_shaping_controller/${ARM_SIDE_PREFIX}_1_joint/effort"
      ${ARM_SIDE_PREFIX}_2_joint:
        command_interface: "${ARM_SIDE_PREFIX}_2_joint_inertia_shaping_controller/${ARM_SIDE_PREFIX}_2_joint/effort"
      ${ARM_SIDE_PREFIX}_3_joint:
        command_interface: "${ARM_SIDE_PREFIX}_3_joint_inertia_shaping_controller/${ARM_SIDE_PREFIX}_3_joint/effort"
      ${ARM_SIDE_PREFIX}_4_joint:
        command_interface: "${ARM_SIDE_PREFIX}_4_joint_inertia_shaping_controller/${ARM_SIDE_PREFIX}_4_joint/effort"
      ${ARM_SIDE_PREFIX}_5_joint:
        command_interface: "${ARM_SIDE_PREFIX}_5_joint_inertia_shaping_controller/${ARM_SIDE_PREFIX}_5_joint/effort"
      ${ARM_SIDE_PREFIX}_6_joint:
        command_interface: "${ARM_SIDE_PREFIX}_6_joint_inertia_shaping_controller/${ARM_SIDE_PREFIX}_6_joint/effort"
      ${ARM_SIDE_PREFIX}_7_joint:
        command_interface: "${ARM_SIDE_PREFIX}_7_joint_inertia_shaping_controller/${ARM_SIDE_PREFIX}_7_joint/effort"
