${FT_SIDE_PREFIX}_controller:
  ros__parameters:
    type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
    frame_id: ${WRIST_SIDE_PREFIX}_link
    sensor_name: ${WRIST_SIDE_PREFIX}_sensor
